-- MySQL Script generated by MySQL Workbench
-- Wed Nov 25 00:10:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_filipini
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_filipini
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_filipini` DEFAULT CHARACTER SET utf8 ;
USE `db_filipini` ;

-- -----------------------------------------------------
-- Table `db_filipini`.`UserAcess`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_filipini`.`UserAcess` (
  `idUserAcess` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `tipoUser` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idUserAcess`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_filipini`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_filipini`.`Endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(100) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(100) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEndereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_filipini`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_filipini`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `tipoUser` VARCHAR(100) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(50) NULL,
  `cnpj` VARCHAR(50) NULL,
  `Endereco_idEndereco` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  INDEX `fk_CreateUser_Endereco1_idx` (`Endereco_idEndereco` ASC) VISIBLE,
  CONSTRAINT `fk_CreateUser_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco`)
    REFERENCES `db_filipini`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_filipini`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_filipini`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `marca` VARCHAR(100) NOT NULL,
  `fornecedor` VARCHAR(100) NOT NULL,
  `validade` VARCHAR(45) NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_filipini`.`Vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_filipini`.`Vendas` (
  `idVendas` INT NOT NULL AUTO_INCREMENT,
  `formaPgto` VARCHAR(100) NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idVendas`),
  INDEX `fk_Vendas_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Vendas_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `db_filipini`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_filipini`.`Produto_has_Vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_filipini`.`Produto_has_Vendas` (
  `Produto_Vendas` VARCHAR(45) NOT NULL,
  `Vendas_idVendas` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  INDEX `fk_Produto_has_Vendas_Vendas1_idx` (`Vendas_idVendas` ASC) VISIBLE,
  INDEX `fk_Produto_has_Vendas_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  PRIMARY KEY (`Produto_Vendas`),
  CONSTRAINT `fk_Produto_has_Vendas_Vendas1`
    FOREIGN KEY (`Vendas_idVendas`)
    REFERENCES `db_filipini`.`Vendas` (`idVendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Vendas_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `db_filipini`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
