-- MySQL Script generated by MySQL Workbench
-- Tue Nov 17 00:56:07 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_filipini
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_filipini
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_filipini` DEFAULT CHARACTER SET utf8 ;
USE `db_filipini` ;

-- -----------------------------------------------------
-- Table `db_filipini`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_filipini`.`enderecos` (
  `idEnderecos` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(100) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  `cep` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idEnderecos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_filipini`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_filipini`.`produtos` (
  `idProdutos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `marca` VARCHAR(50) NOT NULL,
  `fornecedor` VARCHAR(50) NOT NULL,
  `validade` VARCHAR(50) NOT NULL,
  `preço` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idProdutos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_filipini`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_filipini`.`usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(150) NOT NULL,
  `tipo` VARCHAR(30) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `fone` VARCHAR(20) NOT NULL,
  `email` VARCHAR(20) NOT NULL,
  `cpf` VARCHAR(20) NOT NULL,
  `enderecos_idEnderecos` INT NOT NULL,
  PRIMARY KEY (`idUsuarios`, `enderecos_idEnderecos`),
  INDEX `fk_usuarios_enderecos_idx` (`enderecos_idEnderecos` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_enderecos`
    FOREIGN KEY (`enderecos_idEnderecos`)
    REFERENCES `db_filipini`.`enderecos` (`idEnderecos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_filipini`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_filipini`.`vendas` (
  `idVendas` INT NOT NULL AUTO_INCREMENT,
  `formaPgto` VARCHAR(50) NOT NULL,
  `usuarios_id_usuarios` INT NOT NULL,
  `usuarios_enderecos_id_enderecos` INT NOT NULL,
  `usuarios_idUsuarios` INT NOT NULL,
  `usuarios_enderecos_idEnderecos` INT NOT NULL,
  PRIMARY KEY (`idVendas`, `usuarios_id_usuarios`, `usuarios_enderecos_id_enderecos`, `usuarios_idUsuarios`, `usuarios_enderecos_idEnderecos`),
  INDEX `fk_vendas_usuarios1_idx` (`usuarios_idUsuarios` ASC, `usuarios_enderecos_idEnderecos` ASC) VISIBLE,
  CONSTRAINT `fk_vendas_usuarios1`
    FOREIGN KEY (`usuarios_idUsuarios` , `usuarios_enderecos_idEnderecos`)
    REFERENCES `db_filipini`.`usuarios` (`idUsuarios` , `enderecos_idEnderecos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_filipini`.`produtos_vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_filipini`.`produtos_vendas` (
  `idProduto_vendas` INT NOT NULL,
  `vendas_idVendas` INT NOT NULL,
  `produtos_idProdutos` INT NOT NULL,
  PRIMARY KEY (`idProduto_vendas`),
  INDEX `fk_produtos_has_vendas_vendas1_idx` (`vendas_idVendas` ASC) VISIBLE,
  INDEX `fk_produtos_has_vendas_produtos1_idx` (`idProduto_vendas` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_has_vendas_produtos1`
    FOREIGN KEY (`idProduto_vendas`)
    REFERENCES `db_filipini`.`produtos` (`idProdutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_has_vendas_vendas1`
    FOREIGN KEY (`vendas_idVendas`)
    REFERENCES `db_filipini`.`vendas` (`idVendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
