-- -- MySQL Script generated by MySQL Workbench
-- -- Fri Nov 13 21:52:44 2020
-- -- Model: New Model    Version: 1.0
-- -- MySQL Workbench Forward Engineering

-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -- -----------------------------------------------------
-- -- Schema embutidos_filipiniDB
-- -- -----------------------------------------------------

-- -- -----------------------------------------------------
-- -- Schema embutidos_filipiniDB
-- -- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `embutidos_filipiniDB` ;
-- USE `embutidos_filipiniDB` ;

-- -- -----------------------------------------------------
-- -- Table `embutidos_filipiniDB`.`produtos`
-- -- -----------------------------------------------------
-- CREATE TABLE IF NOT EXISTS `embutidos_filipiniDB`.`produtos` (
--   `id_produtos` INT NULL AUTO_INCREMENT,
--   `nome` VARCHAR(100) NOT NULL,
--   `marca` VARCHAR(45) NULL,
--   `fornecedor` VARCHAR(45) NULL,
--   `validade` VARCHAR(45) NULL,
--   `preco` VARCHAR(45) NULL,
--   PRIMARY KEY (`id_produtos`));


-- -- -----------------------------------------------------
-- -- Table `embutidos_filipiniDB`.`enderecos`
-- -- -----------------------------------------------------
-- CREATE TABLE IF NOT EXISTS `embutidos_filipiniDB`.`enderecos` (
--   `id_enderecos` INT NOT NULL AUTO_INCREMENT,
--   `rua` VARCHAR(45) NOT NULL,
--   `numero` VARCHAR(45) NOT NULL,
--   `bairro` VARCHAR(45) NOT NULL,
--   `cidade` VARCHAR(45) NOT NULL,
--   PRIMARY KEY (`id_enderecos`))
-- ENGINE = InnoDB;


-- -- -----------------------------------------------------
-- -- Table `embutidos_filipiniDB`.`usuarios`
-- -- -----------------------------------------------------
-- CREATE TABLE IF NOT EXISTS `embutidos_filipiniDB`.`usuarios` (
--   `id_usuarios` INT NULL AUTO_INCREMENT,
--   `login` VARCHAR(100) NOT NULL,
--   `senha` VARCHAR(100) NOT NULL,
--   `tipo` VARCHAR(15) NULL DEFAULT NULL,
--   `nome` VARCHAR(45) NULL,
--   `fone` VARCHAR(15) NULL,
--   `email` VARCHAR(45) NULL,
--   `cpf` VARCHAR(15) NOT NULL,
--   `enderecos_id_enderecos` INT NOT NULL,
--   PRIMARY KEY (`id_usuarios`),
--   INDEX `fk_usuarios_enderecos1_idx` (`enderecos_id_enderecos` ASC) VISIBLE,
--   CONSTRAINT `fk_usuarios_enderecos1`
--     FOREIGN KEY (`enderecos_id_enderecos`)
--     REFERENCES `embutidos_filipiniDB`.`enderecos` (`id_enderecos`)
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION);


-- -- -----------------------------------------------------
-- -- Table `embutidos_filipiniDB`.`vendas`
-- -- -----------------------------------------------------
-- CREATE TABLE IF NOT EXISTS `embutidos_filipiniDB`.`vendas` (
--   `id_vendas` INT NULL DEFAULT NULL AUTO_INCREMENT,
--   `forma_pagto` VARCHAR(45) NOT NULL,
--   `usuarios_id_usuarios` INT NOT NULL,
--   PRIMARY KEY (`id_vendas`),
--   INDEX `fk_vendas_usuarios1_idx` (`usuarios_id_usuarios` ASC) VISIBLE,
--   CONSTRAINT `fk_vendas_usuarios1`
--     FOREIGN KEY (`usuarios_id_usuarios`)
--     REFERENCES `embutidos_filipiniDB`.`usuarios` (`id_usuarios`)
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION);


-- -- -----------------------------------------------------
-- -- Table `embutidos_filipiniDB`.`vendas_has_produtos`
-- -- -----------------------------------------------------
-- CREATE TABLE IF NOT EXISTS `embutidos_filipiniDB`.`vendas_has_produtos` (
--   `vendas_id_vendas` INT NOT NULL,
--   `produtos_id_produtos` INT NOT NULL,
--   PRIMARY KEY (`vendas_id_vendas`, `produtos_id_produtos`),
--   INDEX `fk_vendas_has_produtos_produtos1_idx` (`produtos_id_produtos` ASC) VISIBLE,
--   INDEX `fk_vendas_has_produtos_vendas1_idx` (`vendas_id_vendas` ASC) VISIBLE,
--   CONSTRAINT `fk_vendas_has_produtos_vendas1`
--     FOREIGN KEY (`vendas_id_vendas`)
--     REFERENCES `embutidos_filipiniDB`.`vendas` (`id_vendas`)
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION,
--   CONSTRAINT `fk_vendas_has_produtos_produtos1`
--     FOREIGN KEY (`produtos_id_produtos`)
--     REFERENCES `embutidos_filipiniDB`.`produtos` (`id_produtos`)
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION);


-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
